### ISSUE TITLE
tau and epsilon

### ISSUE THREAD

**Issue by T1anZhenYu** [yukkyo/PyTorch-FilterResponseNormalizationLayer#1]
Hello, thanks for your work. 
I have read your codes and found something mismatching with original paper.
The first is the 'tau' in TLU. In paper, it's said that tau is a vector of size num_channels. But in your codes, It's just a single value. 
The second is the epsilon. In paper, it's said when using in conv, epsilon is a constant value of 10^-6. but in your codes , it's a learnable parameter.
Will these mismatches hurt the preformance?

**Comment by yukkyo** [comment]
@T1anZhenYu 
Thank you so much for telling me !!
> The first is the 'tau' in TLU. In paper, it's said that tau is a vector of size num_channels. But in your codes, It's just a single value.

I have not yet found a sentence that supports this indication. 
Can you tell me the relevant part of the paper if it is good? 😢 

> The second is the epsilon. In paper, it's said when using in conv, epsilon is a constant value of 10^-6. but in your codes , it's a learnable parameter.

You are correct. I misread the following sentence 😢 

```text
In our experiments, we show that the learnable parameterization is useful for training InceptionV3 mode
l where the Auxiliary logits head produces 1ˆ1 activation maps, and for the VGG-A [22] architecture that
 uses fully connected layers.
```

**Comment by yukkyo** [comment]
@T1anZhenYu 
I found it !
I will modify it !

```text
Note that the parameters γ, β and τ are vectors of size num channels, 
```
